РК4
java-park-mail-ru/IT-Berries-02-2018 pull request #7
Opened 2018-05-30 10:38 UTC by ElenaOshkina

Мы использовали ScheduledExecutorService  (это было в реквесте к рк3), в классе RemotePointService.
Метод выполнения хода step()  сделали synchronized.
Проверьте, пожалуйста)

2018-05-31 08:53 UTC, KSolovyev commented
1. `private ScheduledFuture future = ` - не используется
2. `GameSession.turn`  - не используется
3. Вообще неиспользуемых переменных очень много. Почистите их, пожалуйста
4. Вы итерируетесь в потоке по games, а это обычный потоконебезопасный список, в который игры добавляются из другого потока. Когда список будет автоматически расширяться, все итераторы станут невалидными. Это первая гонка.
5. `game.getLatestTurnStart()`- поле обычное, меняется из нескольких потоков. Это вторая гонка
6. `game.getTurn()` - аналогично
7. `timeOut()` - будет гонка с ходом игрока

2018-05-31 08:54 UTC, KSolovyev requested changes

2018-05-31 08:54 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/mechanics/game/GameSession.java
> +    public synchronized boolean step(Move move) {
есть замечания

2018-05-31 10:17 UTC, ElenaOshkina commented
@KSolovyev Добрый день) Убрали лишний код, добавили синхронизацию методов и переменную turn сделали volatile, а List  c games сихронизированным.

2018-05-31 10:44 UTC, KSolovyev requested changes

2018-05-31 10:44 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/mechanics/game/GameSession.java
> +    private volatile Turn turn;
Теперь хитрее.
Вы сделали, что изменения видны всем потокам.
А надо, чтобы была гарантия, что сообщение о ходе пошлется только из одного места (либо из таймера, либо из обработчика хода). Сейчас таких гарантий нет
Можете наложить на свою программу аналогию из примера со счетчиком:
у вас потокобезопасная проверка условия (чтение) и потокобезопасная запись (инкремент)
Но вместе эти операции не синхронизированы. Понимаете, что нужно изменить?

2018-05-31 10:47 UTC, KSolovyev requested changes

2018-05-31 10:47 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +    private final List<GameSession> games = Collections.synchronizedList(new ArrayList());
Если почитать джавадок на метод, который вы использовали, то там написано, что итерироваться по такому листу можно только в блоке synchronized

2018-05-31 11:24 UTC, ElenaOshkina commented on src/main/java/com/itberries2018/demo/mechanics/game/GameSession.java
> +    private volatile Turn turn;
Может быть, нужно использовать ReadWriteLock, но я пока не очень понимаю(

2018-05-31 11:24 UTC, ElenaOshkina commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +    private final List<GameSession> games = Collections.synchronizedList(new ArrayList());
да, это поняла, спасибо)

2018-05-31 11:50 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/mechanics/game/GameSession.java
> +    private volatile Turn turn;
я предлагаю сделать final AtomicReference<Turn>
И использовать только атомарные методы типа compareAndExchange

2018-05-31 13:31 UTC, ElenaOshkina commented on src/main/java/com/itberries2018/demo/mechanics/game/GameSession.java
> +    private volatile Turn turn;
А есть ли разница между compareAndExchange  и compareAndSet, они же оба устанавливают новое значение? А так, мы добавили проверку перед изменением значения Turn и сделали его AtomicReference)

2018-05-31 13:36 UTC, ElenaOshkina commented
куда-то пропало сообщение, странно)
А чем отличаются compareAndExchange и compareAndSet, они ведь оба проверяют, а потом устанавливают новое значение?
А так мы добавили final AtomicReference к Turn,  и делаем проверки перед изменением Turn ...

2018-06-01 05:42 UTC, ElenaOshkina commented
@KSolovyev добавила synchronized (game.getTurn()) к обходу игр из обработчика таймера, но разве это помешает другому потоку зайти и сделать game.choseTurn() ? Можно ли сделать внутри цикла  synchronized (game) ?

2018-06-01 10:05 UTC, KSolovyev requested changes

2018-06-01 10:05 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +                    synchronized (game.getTurn()) {
уже лучше, но синхронизация должна быть на один монитор. Можно сделать synchronized (game)

2018-06-01 10:13 UTC, ElenaOshkina commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +                    synchronized (game.getTurn()) {
Ок, добавила синхронизацию на каждую game)

2018-06-01 12:33 UTC, KSolovyev requested changes

2018-06-01 12:33 UTC, KSolovyev commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +                        synchronized (game.getTurn()) {
Не нужно же(. Нигде больше синхронизации на turn нет. Это штука бесполезная. Я про game написал, потому что у вас вся остальная синхронизация сделана на GameSession. И надо было либо там синхронизироваться по turn, либо здесь на game.  Вложенной синхронизации точно не нужно

2018-06-01 13:43 UTC, ElenaOshkina commented on src/main/java/com/itberries2018/demo/websockets/RemotePointService.java
> +                        synchronized (game.getTurn()) {
ааааа.....я неправильно поняла(
убрала вложенную синхронизацию.

2018-06-01 18:17 UTC, KSolovyev commented
С точки зрения многопоточности все. Я вам поставил. Командуйте, когда надо будет мержить

2018-06-01 18:34 UTC, ElenaOshkina commented
@KSolovyev  у нас на фронте потребовали сделать выделенный север, у нас сейчас все там c https и nginx, но если будет нужно - мы напишем)

2018-06-10 20:22 UTC, merged